version: '3'

services:
  mi_postgres:
    image: postgres:latest
    container_name: mi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: basededatos
    ports:
      - "5555:5432"

  postgres_api:
    image: postgres:latest
    container_name: postgres_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: apibd
    ports:
      - "5555:5432"